@extends('layouts.app')
@section('title', 'Procurement and Financial Requests')
@section('content')
<div class="page-header"><div><h2>Procurement and Financial Requests</h2><p class="page-subtitle">Centralized entry point — link to Budget / Allocation / Expense / Payable via FK instead of duplicating.</p></div><div style="display:flex;gap:8px;"><a href="{{ route('accountant.procurement.index') }}" class="btn btn-secondary">View Procurement Requests</a><a href="{{ route('accountant.financial-requests.create') }}" class="btn btn-primary">Prepare Request</a></div></div>
<div class="dashboard-card"><form method="GET" class="filter-form" style="align-items:flex-end;">
<div class="form-group" style="flex:0 1 200px;min-width:160px;"><label>Search</label><input type="text" name="search" class="form-control" value="{{ request('search') }}" placeholder="Request no. / description"></div>
<div class="form-group" style="min-width:160px;"><label>Request Type</label><select name="request_type" class="form-control"><option value="">All types</option>@foreach(\App\Models\FinancialRequest::TYPES as $t)<option value="{{ $t }}" {{ request('request_type')===$t?'selected':'' }}>{{ ucfirst(str_replace('_',' ',$t)) }}</option>@endforeach</select></div>
<div class="form-group" style="min-width:160px;"><label>Status</label><select name="status" class="form-control"><option value="">All statuses</option>@foreach(\App\Models\FinancialRequest::STATUSES as $s)<option value="{{ $s }}" {{ request('status')===$s?'selected':'' }}>{{ ['draft'=>'Draft','submitted'=>'Submitted','under_review'=>'Under Review','approved'=>'Approved','rejected'=>'Rejected','for_revision'=>'For Revision','completed'=>'Completed'][$s] ?? ucfirst(str_replace('_',' ',$s)) }}</option>@endforeach</select></div>
<div style="display:flex;gap:8px;"><button class="btn btn-secondary">Filter</button><a href="{{ route('accountant.financial-requests.index') }}" class="btn btn-secondary">Clear</a></div>
</form>
<div class="table-responsive"><table class="table"><thead><tr><th>Request No. + Type</th><th>Budget ID</th><th>Linked Record</th><th style="text-align:right;">Items</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>
@forelse($records as $r)@php $ic = is_array($r->metadata ?? null) ? count($r->metadata['items'] ?? []) : 0; $bId = $r->budget_plan_id ?? (($r->reference_type === \App\Models\BudgetPlan::class) ? $r->reference_id : null); @endphp<tr><td><strong>{{ $r->request_number }}</strong><br><span class="summary-desc">{{ $r->request_type }} · {{ $r->department }}</span></td><td>@if($bId)<strong>#{{ $bId }}</strong>@if($r->budgetPlan)<br><span class="summary-desc">{{ $r->budgetPlan->budget_name }}</span>@endif@else<span class="summary-desc">—</span>@endif</td><td>{{ $r->reference_type ? class_basename($r->reference_type).' #'.$r->reference_id : '—' }}</td><td style="text-align:right;">{{ $ic ?: '—' }}</td><td>₱{{ number_format($r->amount,2) }}</td><td>@include('accountant.partials.status-badge',['status'=>$r->status])</td><td><a href="{{ route('accountant.financial-requests.show',$r) }}" class="btn btn-sm btn-secondary">Open</a></td></tr>
@empty<tr><td colspan="7"></td></tr>@endforelse
</tbody></table></div>{{ $records->links() }}</div>
@endsection
